/**
 * Generated by kysely-codegen, then manually adjusted.
 * Re-generate with: DATABASE_URL=... bunx kysely-codegen --out-file ./src/kysely-types.ts --dialect postgres
 * After re-generating, re-apply manual edits (remove drizzle migrations table).
 */

import type { ColumnType } from "kysely";

export type AttestationType = "confirmed" | "disputed" | "originated" | "qualified";

export type CitationSource = "exhaustive_sweep" | "research_pipeline" | "steward";

export type CitationStatus = "fully_cited" | "partially_cited" | "uncited";

export type CitationSupportType = "direct" | "partial" | "tension";

export type CompositionTool = "ask" | "poll" | "review";

export type ConsensusStatus = "debated" | "partial" | "strong" | "unverified";

export type EditionStatus = "failed" | "pending" | "processing" | "ready";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type JobPriority = "critical" | "high" | "low" | "normal";

export type JobStatus = "completed" | "failed" | "pending" | "processing";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type ModerationStatus = "approved" | "pending_review" | "removed";

export type QueryClaimRelationship = "generated" | "reused";

export type ResultStatus = "completed" | "failed" | "pending" | "processing";

export type ResultToolType = "ask" | "poll" | "research" | "review" | "super_poll";

export type ReviewFileStatus = "failed" | "pending" | "processing" | "ready" | "uploaded";

export type TheologianEra = "Apostolic" | "Medieval" | "Modern" | "Patristic" | "Post-Reformation" | "Reformation";

export type TheologianTradition = "Anglican" | "Baptist" | "Catholic" | "Lutheran" | "Methodist" | "Neo-Orthodox" | "Orthodox" | "Puritan" | "Reformed";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Annotations {
  author_id: string;
  body: string;
  claim_id: string;
  created_at: Generated<Timestamp>;
  helpful_count: Generated<number>;
  id: Generated<string>;
  parent_annotation_id: string | null;
}

export interface Attestations {
  attestation_method: Json | null;
  attestation_type: AttestationType;
  claim_id: string;
  detail: string | null;
  detail_embedding: string | null;
  evaluated_at: Generated<Timestamp>;
  id: Generated<string>;
  model_id: string;
}

export interface ClaimCitations {
  added_at: Generated<Timestamp>;
  added_by: CitationSource;
  claim_id: string;
  id: Generated<string>;
  location: string | null;
  original_text: string | null;
  support_type: CitationSupportType;
  translation: string | null;
  verified_by_models: Generated<Json | null>;
  work_author: string;
  work_title: string;
}

export interface Claims {
  citation_status: Generated<CitationStatus>;
  consensus_status: Generated<ConsensusStatus>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  proposition: string;
  proposition_embedding: string | null;
  succeeded_by: string | null;
  succession_reason: string | null;
  theologian_id: string;
  topic_id: string | null;
}

export interface ClaimSaves {
  claim_id: string;
  created_at: Generated<Timestamp>;
  user_id: string;
}

export interface CollectionResults {
  added_at: Generated<Timestamp>;
  collection_id: string;
  composition_id: string | null;
  id: Generated<string>;
  position: Generated<number>;
  result_id: string | null;
}

export interface Collections {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  position: number | null;
  slug: string;
  status: Generated<string>;
  subtitle: string | null;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface CompositionClaims {
  claim_id: string;
  display_order: number;
  relevance_score: number | null;
  theologian_composition_id: string;
}

export interface Compositions {
  completed_at: Timestamp | null;
  content_key: string | null;
  created_at: Generated<Timestamp>;
  error_message: string | null;
  generation_method: Json | null;
  hidden_at: Timestamp | null;
  id: Generated<string>;
  is_canonical: Generated<boolean>;
  is_private: Generated<boolean>;
  job_id: string | null;
  moderation_status: Generated<ModerationStatus>;
  pdf_key: string | null;
  query_id: string | null;
  question_embedding: string | null;
  question_text: string;
  save_count: Generated<number>;
  share_image_key: string | null;
  slug: string | null;
  source_result_id: string | null;
  status: Generated<ResultStatus>;
  synthesis: Json | null;
  team_snapshot: Json;
  tool: CompositionTool;
  updated_at: Generated<Timestamp>;
  user_id: string;
  view_count: Generated<number>;
}

export interface CompositionSaves {
  composition_id: string;
  created_at: Generated<Timestamp>;
  user_id: string;
}

export interface CompositionViews {
  composition_id: string;
  id: Generated<string>;
  period_end: Generated<Timestamp>;
  period_start: Generated<Timestamp>;
  view_count: Generated<number>;
}

export interface ContentFlags {
  admin_note: string | null;
  claim_id: string | null;
  composition_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  reason: string | null;
  reporter_id: string | null;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  result_id: string | null;
  status: Generated<string>;
  type: string;
}

export interface Editions {
  content_type: string | null;
  created_at: Generated<Timestamp>;
  error_message: string | null;
  id: Generated<string>;
  label: string;
  language: string;
  license: string | null;
  paragraph_count: Generated<number>;
  publisher: string | null;
  source_storage_key: string | null;
  source_url: string | null;
  status: Generated<EditionStatus>;
  translator: string | null;
  updated_at: Generated<Timestamp>;
  work_id: string;
}

export interface InferenceLogs {
  attribution: Generated<Json>;
  completion_tokens: Generated<number>;
  created_at: Generated<Timestamp>;
  duration_seconds: number | null;
  id: Generated<string>;
  model: string;
  prompt_tokens: Generated<number>;
  source: string;
}

export interface Jobs {
  attempts: Generated<number>;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  error_details: Json | null;
  error_message: string | null;
  id: Generated<string>;
  locked_at: Timestamp | null;
  locked_by: string | null;
  max_attempts: Generated<number>;
  payload: Generated<Json>;
  priority: Generated<JobPriority>;
  result: Json | null;
  scheduled_for: Timestamp | null;
  started_at: Timestamp | null;
  status: Generated<JobStatus>;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface Nodes {
  canonical_ref: string | null;
  created_at: Generated<Timestamp>;
  depth: number;
  edition_id: string;
  embed_method: string | null;
  embedding: string | null;
  heading: string | null;
  id: Generated<string>;
  parent_id: string | null;
  sort_order: number;
}

export interface NodeSummaries {
  created_at: Generated<Timestamp>;
  embedding_text: string | null;
  id: Generated<string>;
  language: Generated<string>;
  model: string | null;
  node_id: string;
  summary: Json;
}

export interface Paragraphs {
  canonical_ref: string | null;
  created_at: Generated<Timestamp>;
  embed_method: string | null;
  embedding: string | null;
  id: Generated<string>;
  language: string | null;
  node_id: string;
  normalized_text: string | null;
  page_end: number | null;
  page_start: number | null;
  search_vector: Generated<string | null>;
  sort_order: number;
  text: string;
}

export interface ParagraphTranslations {
  created_at: Generated<Timestamp>;
  embed_method: string | null;
  embedding: string | null;
  id: Generated<string>;
  language: Generated<string>;
  model: string | null;
  paragraph_id: string;
  search_vector: Generated<string | null>;
  source: string | null;
  text: string;
}

export interface Queries {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  question_embedding: string | null;
  question_text: string;
}

export interface QueryClaims {
  claim_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  query_id: string;
  relationship: QueryClaimRelationship;
  saturation_pass: number | null;
  theologian_id: string;
}

export interface QueryTheologianSaturations {
  created_at: Generated<Timestamp>;
  desaturated_at: Timestamp | null;
  desaturation_reason: string | null;
  id: Generated<string>;
  is_saturated: Generated<boolean>;
  models_used: Generated<Json>;
  passes_completed: Generated<number>;
  query_id: string;
  saturated_at: Timestamp | null;
  theologian_id: string;
}

export interface ResultProgressLogs {
  composition_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  message: string;
  metadata: Json | null;
  result_id: string | null;
}

export interface Results {
  algorithm_version: string | null;
  completed_at: Timestamp | null;
  content_key: string | null;
  created_at: Generated<Timestamp>;
  embedded_question: string | null;
  error_message: string | null;
  hidden_at: Timestamp | null;
  id: Generated<string>;
  input_payload: Json;
  is_private: Generated<boolean>;
  job_id: string | null;
  models: Json | null;
  moderation_status: Generated<ModerationStatus>;
  pdf_job_id: string | null;
  pdf_key: string | null;
  preview_data: Json | null;
  preview_excerpt: string | null;
  result_type_id: string | null;
  retried_from_id: string | null;
  review_file_id: string | null;
  save_count: Generated<number>;
  search_vector: string | null;
  share_image_key: string | null;
  status: Generated<ResultStatus>;
  team_snapshot_id: string | null;
  theologian_id: string | null;
  title: string;
  token_usage: Json | null;
  tool_type: ResultToolType;
  updated_at: Generated<Timestamp>;
  user_id: string;
  view_count: Generated<number>;
}

export interface ResultSaves {
  created_at: Generated<Timestamp>;
  result_id: string;
  user_id: string;
}

export interface ResultTypes {
  content_schema: Json;
  created_at: Generated<Timestamp>;
  description: string;
  id: Generated<string>;
  input_schema: Json;
  is_active: Generated<boolean>;
  kind: ResultToolType;
  preview_schema: Json;
  version: number;
}

export interface ResultViews {
  id: Generated<string>;
  period_end: Generated<Timestamp>;
  period_start: Generated<Timestamp>;
  result_id: string;
  view_count: Generated<number>;
}

export interface ReviewFiles {
  char_count: number | null;
  content_type: string;
  created_at: Generated<Timestamp>;
  error_message: string | null;
  file_key: string;
  file_name: string;
  id: Generated<string>;
  job_id: string | null;
  label: string;
  status: Generated<ReviewFileStatus>;
  text_storage_key: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface TeamMemberships {
  team_id: string;
  theologian_id: string;
}

export interface Teams {
  created_at: Generated<Timestamp>;
  description: string | null;
  display_order: Generated<number>;
  id: Generated<string>;
  is_native: Generated<boolean>;
  name: string;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
  version: Generated<number>;
  visible: Generated<boolean>;
}

export interface TeamSnapshots {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  members: Json;
  name: string;
  team_id: string;
  version: number;
}

export interface TheologianCompositions {
  composition_id: string;
  created_at: Generated<Timestamp>;
  display_order: number;
  generation_method: Json | null;
  id: Generated<string>;
  synthesis: Json | null;
  theologian_id: string;
}

export interface Theologians {
  bio: string | null;
  born: number | null;
  created_at: Generated<Timestamp>;
  died: number | null;
  era: TheologianEra | null;
  has_research: Generated<boolean>;
  id: Generated<string>;
  image_key: string | null;
  initials: string | null;
  key_works: Generated<string[]>;
  language_primary: string | null;
  name: string;
  slug: string;
  tagline: string | null;
  tradition: TheologianTradition | null;
  updated_at: Generated<Timestamp>;
  voice_style: string | null;
}

export interface Topics {
  claim_count: Generated<number>;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  name: string;
  slug: string;
  topic_embedding: string | null;
}

export interface UsageLogs {
  composition_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  result_id: string | null;
  team_size: number | null;
  tool_type: string;
  user_id: string;
}

export interface UsageOverrides {
  admin_id: string | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  id: Generated<string>;
  max_team_size: number | null;
  monthly_limit: number;
  reason: string | null;
  tool_type: string;
  user_id: string;
}

export interface Users {
  clerk_id: string;
  created_at: Generated<Timestamp>;
  email: string | null;
  id: Generated<string>;
  image_url: string | null;
  name: string | null;
  tier: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface WaitlistSignups {
  created_at: Generated<Timestamp>;
  email: string;
  email_confirmed: Generated<boolean>;
  first_question: string | null;
  id: Generated<string>;
  queue_position: number;
  referral_code: string;
  referral_count: Generated<number>;
  referred_by: string | null;
  survey_responses: Json | null;
  utm_campaign: string | null;
  utm_medium: string | null;
  utm_source: string | null;
}

export interface Works {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  original_language: string | null;
  slug: string;
  theologian_id: string;
  title: string;
  updated_at: Generated<Timestamp>;
  year_max: number | null;
  year_min: number | null;
}

export interface DB {
  annotations: Annotations;
  attestations: Attestations;
  claim_citations: ClaimCitations;
  claim_saves: ClaimSaves;
  claims: Claims;
  collection_results: CollectionResults;
  collections: Collections;
  composition_claims: CompositionClaims;
  composition_saves: CompositionSaves;
  composition_views: CompositionViews;
  compositions: Compositions;
  content_flags: ContentFlags;
  editions: Editions;
  inference_logs: InferenceLogs;
  jobs: Jobs;
  node_summaries: NodeSummaries;
  nodes: Nodes;
  paragraph_translations: ParagraphTranslations;
  paragraphs: Paragraphs;
  queries: Queries;
  query_claims: QueryClaims;
  query_theologian_saturations: QueryTheologianSaturations;
  result_progress_logs: ResultProgressLogs;
  result_saves: ResultSaves;
  result_types: ResultTypes;
  result_views: ResultViews;
  results: Results;
  review_files: ReviewFiles;
  team_memberships: TeamMemberships;
  team_snapshots: TeamSnapshots;
  teams: Teams;
  theologian_compositions: TheologianCompositions;
  theologians: Theologians;
  topics: Topics;
  usage_logs: UsageLogs;
  usage_overrides: UsageOverrides;
  users: Users;
  waitlist_signups: WaitlistSignups;
  works: Works;
}
